Rewrite local README with updated startup instructions
slimsag/mach-glfw pull request #44
Opened 2024-07-29 22:42 UTC by jempiere

This document maintains most of the original language in the previous README, while incorporating a modernized version of the information found [here](https://machengine.org/v0.4/pkg/mach-glfw/). This project and its test provided here executes as-intended with zig version `0.13.0-dev.351+64ef45eb0` on macos-aarch64.

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

2024-08-26 17:24 UTC, terraquad requested changes
Looks good overall, but the syntax highlighting uses the wrong programming language.

2024-08-26 17:24 UTC, terraquad commented on README.md
> +zig fetch --save "https://pkg.machengine.org/mach-glfw/LATEST_COMMIT.tar.gz"
Since this isn't a mach project anymore, I would write this instead:

```sh
$ zig fetch --save git+https://github.com/slimsag/mach-glfw
```

This will automatically resolve to the latest commit.

2024-08-26 17:24 UTC, terraquad commented on README.md
> +```typescript
Should be ` ```zig `

2024-08-26 17:24 UTC, terraquad commented on README.md
> +```typescript
Should be ` ```zig `

2024-08-26 17:24 UTC, terraquad commented on README.md
> +```typescript
Should probably be ` ```zig `, but I'm not sure since it is a .zon file.

Edit: It should be ` ```zig `, I tested it and it provides better syntax highlighting even on .zon

2024-08-26 17:24 UTC, terraquad commented on README.md
> +```typescript
Should be ` ```zig `

2024-08-26 17:24 UTC, terraquad commented on README.md
> +            .url = "https://pkg.machengine.org/mach-glfw/FULL_HASH_LATEST_COMMIT.tar.gz",
Again, I would change this to:

```zig
.url = "git+https://github.com/slimsag/mach-glfw#[latest-commit-hash]"
```

2024-08-26 17:24 UTC, terraquad commented on README.md
> +            .hash = "" // place anything here--zig build will error and give you the correct hash
Remove this line, as it being present makes Zig assume the hash should be `""`. It'll only tell you the correct hash when this line is not present.

2024-09-22 07:21 UTC, dandeduck commented on README.md
> + - OpenGL: [castholm/zigglegen](https://github.com/hexops/mach-glfw-opengl-example) - [example](https://github.com/hexops/mach-glfw-opengl-example)
Not a link to zigglgen

2024-09-22 08:03 UTC, terraquad commented on README.md
> + - OpenGL: [castholm/zigglegen](https://github.com/hexops/mach-glfw-opengl-example) - [example](https://github.com/hexops/mach-glfw-opengl-example)
Should be `https://github.com/castholm/zigglgen`

2024-12-01 10:06 UTC, terraquad commented on README.md
> + - OpenGL: [castholm/zigglegen](https://github.com/hexops/mach-glfw-opengl-example) - [example](https://github.com/hexops/mach-glfw-opengl-example)
> Not a link to zigglegen

As seen on https://machengine.org/v0.4/pkg/mach-glfw/ it links to `zigglgen`

2024-12-21 21:10 UTC, closed without merging

2024-12-21 21:13 UTC, castholm commented
Thanks, and sorry it took so long to get to this PR. I think including the startup instructions in the README would be useful, so I adapted some of your changes into #51.